apiVersion: batch/v1
kind: Job
metadata:
  name: mongodb-init
  annotations:
    helm.sh/hook: post-install,post-upgrade
    helm.sh/hook-weight: "5"
    helm.sh/hook-delete-policy: before-hook-creation
spec:
  template:
    spec:
      restartPolicy: OnFailure
      containers:
        - name: mongo-init
          image: mongo:7.0
          resources:
            requests:
              cpu: "50m"
              memory: "64Mi"
            limits:
              cpu: "200m"
              memory: "512Mi"
          command:
            - mongosh
            - "mongodb://root:rootpassword@mongodb:27017/admin"
            - --eval
            - |
              db.getSiblingDB("sausage-store").createUser({
                user: "reports",
                pwd: "reportspassword",
                roles: [{ role: "readWrite", db: "sausage-store" }]
              })
